# Generated by Django 5.0.7 on 2024-07-23 10:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Form2',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateField(verbose_name='Дата начала отчетного периода')),
                ('end_date', models.DateField(verbose_name='Дата окончания отчетного периода')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время добавления записи в БД')),
            ],
            options={
                'verbose_name': 'Шапка месячных форм молодых специалистов',
                'verbose_name_plural': 'Шапки месячных форм молодых специалистов',
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Название организации')),
            ],
            options={
                'verbose_name': 'Организация',
                'verbose_name_plural': 'Организации',
            },
        ),
        migrations.CreateModel(
            name='Form1',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('article_name', models.CharField(max_length=255, verbose_name='Наименование статьи')),
                ('order', models.IntegerField(verbose_name='Порядок следования статей')),
                ('valid_until', models.DateField(verbose_name='Дата, до которой является актуальной')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='Дата и время последнего изменения записи')),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Имя пользователя, изменившего запись')),
            ],
            options={
                'verbose_name': 'Показатели молодых специалистов',
                'verbose_name_plural': 'Показатели молодых специалистов',
            },
        ),
        migrations.CreateModel(
            name='Form3',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('distribution_count', models.IntegerField(verbose_name='Количество молодых специалистов по Распределению')),
                ('target_distribution_count', models.IntegerField(verbose_name='Количество молодых специалистов по Целевому распределению')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='Дата и время последнего изменения записи')),
                ('form1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.form1', verbose_name='Связь с формой 1')),
                ('form2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.form2', verbose_name='Связь с формой 2')),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Имя пользователя, изменившего запись')),
            ],
            options={
                'verbose_name': 'Линии месячных форм молодых специалистов',
                'verbose_name_plural': 'Линии месячных форм молодых специалистов',
            },
        ),
        migrations.AddField(
            model_name='form2',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.organization', verbose_name='Организация'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.organization')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профиль пользователя',
                'verbose_name_plural': 'Профили пользователей',
            },
        ),
    ]
