# Generated by Django 5.0.7 on 2024-07-26 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_userprofile_organization'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialistDismissalReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(max_length=255)),
                ('total_young_specialists', models.IntegerField(blank=True, null=True)),
                ('commission_referred_total', models.IntegerField(blank=True, null=True)),
                ('total_dismissed_specialists', models.IntegerField(blank=True, null=True)),
                ('term_expired_total', models.IntegerField(blank=True, null=True)),
                ('military_service_total', models.IntegerField(blank=True, null=True)),
                ('education_institution_total', models.IntegerField(blank=True, null=True)),
                ('relocation_total', models.IntegerField(blank=True, null=True)),
                ('discrediting_circumstances_total', models.IntegerField(blank=True, null=True)),
                ('housing_absence_total', models.IntegerField(blank=True, null=True)),
                ('rep_beg_period', models.DateField()),
                ('rep_end_period', models.DateField()),
            ],
            options={
                'db_table': 'source_table',
            },
        ),
    ]
