# Generated by Django 5.0.7 on 2024-07-27 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_specialistdismissalreport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialistdismissalreport',
            name='rep_beg_period',
        ),
        migrations.RemoveField(
            model_name='specialistdismissalreport',
            name='rep_end_period',
        ),
        migrations.AddField(
            model_name='specialistdismissalreport',
            name='commission_referred_distribution',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='specialistdismissalreport',
            name='commission_referred_target',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='specialistdismissalreport',
            name='discrediting_circumstances_distribution',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='specialistdismissalreport',
            name='discrediting_circumstances_target',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='specialistdismissalreport',
            name='education_institution_distribution',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='specialistdismissalreport',
            name='education_institution_target',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='specialistdismissalreport',
            name='housing_absence_distribution',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='specialistdismissalreport',
            name='housing_absence_target',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='specialistdismissalreport',
            name='military_service_distribution',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='specialistdismissalreport',
            name='military_service_target',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='specialistdismissalreport',
            name='relocation_distribution',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='specialistdismissalreport',
            name='relocation_target',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='specialistdismissalreport',
            name='term_expired_target',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
