# Generated by Django 5.0.7 on 2024-07-27 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_specialistdismissalreport_rep_beg_period_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialistdismissalreport',
            name='term_expired_distribution',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
