# Generated by Django 5.0.7 on 2024-07-26 18:39

from django.db import migrations


class Migration(migrations.Migration):

    operations = [
        migrations.RunSQL(
            sql="""
                CREATE TABLE source_table (
                    id serial PRIMARY KEY,
                    organization_name varchar(255),
                    total_young_specialists integer,
                    commission_referred_total integer,
                    commission_referred_target integer,
                    commission_referred_distribution integer,
                    total_dismissed_specialists integer,
                    term_expired_total integer,
                    term_expired_target integer,
                    term_expired_distribution integer,
                    military_service_total integer,
                    military_service_target integer,
                    military_service_distribution integer,
                    education_institution_total integer,
                    education_institution_target integer,
                    education_institution_distribution integer,
                    relocation_total integer,
                    relocation_target integer,
                    relocation_distribution integer,
                    discrediting_circumstances_total integer,
                    discrediting_circumstances_target integer,
                    discrediting_circumstances_distribution integer,
                    housing_absence_total integer,
                    housing_absence_target integer,
                    housing_absence_distribution integer,
                );
                """,
            reverse_sql="DROP TABLE source_table;"
        ),
    ]